src/components/bulk-email-tool/InstructorBulkEmailTool.jsx, src/components/bulk-email-tool/api.js, src/index.jsx
A little more scaffolding. We need proper routing and passing of the courseId to the subcomponents.
=> feat:[MICROBA-1618] Add proper routing and some data

src/components/bulk-email-tool/bulk-email-task-manager/BulkEmailContentHistory.jsx, src/components/bulk-email-tool/bulk-email-task-manager/BulkEmailPendingTasks.jsx, src/components/bulk-email-tool/bulk-email-task-manager/BulkEmailTaskHistory.jsx, src/components/bulk-email-tool/bulk-email-task-manager/api.js
[MICROBA-1621]
* Add support to the Instructor Dashboard `list_instructor_tasks`, `list_email_content`, and `list_background_email_tasks`  REST API endpoints of edx-platform.
=> feat: add API calls to get data needed by the bulk email task manager section

package-lock.json, package.json, src/components/bulk-email-tool/BulkEmailBody.jsx, src/components/bulk-email-tool/BulkEmailTool.jsx, src/components/bulk-email-tool/TextEditor.jsx, src/utils/useMobileResponsive.js, webpack.prod.config.js
Adds the bulk email body, subject, and submit button to the bulk email tool. Not yet wired up.
=> feat: [Microba-1620] Add email form to BulkEmailTool

src/components/bulk-email-tool/bulk-email-task-manager/BulkEmailContentHistory.jsx, src/components/bulk-email-tool/bulk-email-task-manager/BulkEmailPendingTasks.jsx, src/components/bulk-email-tool/bulk-email-task-manager/BulkEmailTaskHistory.jsx, src/components/bulk-email-tool/bulk-email-task-manager/data/__factories__/emailContentHistory.factory.js, src/components/bulk-email-tool/bulk-email-task-manager/data/__factories__/emailTaskHistory.factory.js, src/components/bulk-email-tool/bulk-email-task-manager/data/__factories__/pendingInstructorTask.factory.js, src/components/bulk-email-tool/bulk-email-task-manager/data/api.js, src/components/bulk-email-tool/bulk-email-task-manager/messages.js, src/components/bulk-email-tool/bulk-email-task-manager/test/BulkEmailContentHistory.test.jsx, src/components/bulk-email-tool/bulk-email-task-manager/test/BulkEmailPendingTasks.test.jsx, src/components/bulk-email-tool/bulk-email-task-manager/test/BulkEmailTaskHistory.test.jsx
[MICROBA-1621]
* Fix display bug for the error Alert component found during test writing
* Add tests for BulkEmailTaskHistory component
* Fix bug with a column name in the bulk course email content history table
* Add tests for the BulkEmailContentHistory component
* Add tests for the BulkEmailPendingTasks component
=> feat: add tests for bulk course email task manager components

package-lock.json, package.json, src/components/bulk-email-tool/text-editor/TextEditor.jsx
PR also removed the "powered by tiny" branding on the RTE
=> chore: add edx-next theme to repo

src/components/bulk-email-tool/BulkEmailTool.jsx, src/components/bulk-email-tool/bulk-email-form/BulkEmailForm.jsx, src/components/bulk-email-tool/bulk-email-form/BulkEmailRecipient.jsx, src/components/bulk-email-tool/data/__factories__/cohort.factory.js, src/components/bulk-email-tool/data/api.js, src/components/bulk-email-tool/test/BulkEmailTool.test.jsx
Modifies the recipients section of the email form to show cohorts, if applicable.
=> feat: [MICROBA-1688] Add cohorts to recipients

src/components/bulk-email-tool/text-editor/TextEditor.jsx
=> feat: add features to text editor

package-lock.json, package.json, src/components/bulk-email-tool/bulk-email-context/BulkEmailProvider.jsx, src/components/bulk-email-tool/bulk-email-form/BulkEmailForm.jsx, src/components/bulk-email-tool/bulk-email-form/ScheduleEmailForm.jsx, src/components/bulk-email-tool/bulk-email-form/data/actions.js, src/components/bulk-email-tool/bulk-email-form/data/api.js, src/components/bulk-email-tool/bulk-email-form/data/reducer.js, src/components/bulk-email-tool/bulk-email-form/data/test/reducer.test.js, src/components/bulk-email-tool/bulk-email-form/data/thunks.js, src/components/bulk-email-tool/bulk-email-form/messages.js, src/components/bulk-email-tool/bulk-email-form/test/BulkEmailForm.test.jsx, src/components/bulk-email-tool/bulk-email-task-manager/BulkEmailTaskManager.jsx, src/components/bulk-email-tool/bulk-email-task-manager/ViewEmailModal.jsx, src/components/bulk-email-tool/bulk-email-task-manager/bulk-email-scheduled-emails-table/BulkEmailScheduledEmailsTable.jsx, src/components/bulk-email-tool/bulk-email-task-manager/bulk-email-scheduled-emails-table/data/actions.js, src/components/bulk-email-tool/bulk-email-task-manager/bulk-email-scheduled-emails-table/data/api.js, src/components/bulk-email-tool/bulk-email-task-manager/bulk-email-scheduled-emails-table/data/reducer.js, src/components/bulk-email-tool/bulk-email-task-manager/bulk-email-scheduled-emails-table/data/test/reducer.test.js, src/components/bulk-email-tool/bulk-email-task-manager/bulk-email-scheduled-emails-table/data/thunks.js, src/components/bulk-email-tool/bulk-email-task-manager/bulk-email-scheduled-emails-table/test/BulkEmailScheduledEmailsTable.test.jsx, src/components/bulk-email-tool/bulk-email-task-manager/bulk-email-scheduled-emails-table/test/__factories__/courseEmail.factory.js
This PR adds delete and edit functionality to emails that are scheduled to be sent at a future date. The workflow for editing is as such:
- A user clicks edit on the table
- The contents of the email are copied to the editor, and the user makes edits
- The user is warned that this is editing an email, and that it will not create a new task, instead updating the selected one
- If they accept, the email is updated.
For delete, the user just hits the delete button, and its gone. There is now warning popup as of yet.
This PR also adds the toast component for success and errors when sending emails.
=> feat: [MICROBA-1840] delete/edit scheduled emails

package-lock.json, package.json, src/index.jsx
Major version upgrade of `@edx/paragon`.
=> build: major version upgrade of paragon

src/components/bulk-email-tool/BulkEmailTool.jsx, src/components/bulk-email-tool/bulk-email-task-manager/BulkEmailPendingTasksAlert.jsx, src/components/bulk-email-tool/bulk-email-task-manager/BulkEmailTaskManager.jsx, src/components/bulk-email-tool/bulk-email-task-manager/test/BulkEmailPendingTasksAlert.test.jsx, src/components/navigation-tabs/BackToInstructor.jsx, src/components/navigation-tabs/BackToInstructor.test.jsx
=> Backport fix 126

package-lock.json, package.json
This PR resolves the `PUBLIC_PATH` configuration issue by upgrading frontend-platform from `v5.0.0` to `v5.5.2`.
=> chore: bump frontend-platform (#158)

renovate.json
**Description:**
Add `@openedx` in renovate automate configuration. 
[Create common renovate config that automates @edx and @openedx namespaced minor/patch version upgrades](https://github.com/openedx/wg-frontend/issues/116#event-10495007446)
=> Mashal m/update renovate configuration

src/components/page-container/PageContainer.jsx, src/index.jsx
- Fixed page layout for header and footer (container was move to inner level)
=> feat: Fixed page payout

src/components/page-container/PageContainer.jsx, src/index.jsx
- Fixed page layout for header and footer (container was move to inner level)
=> feat: Fixed page payout (quince.master)

src/components/page-container/PageContainer.jsx, src/index.jsx
- Fixed page layout for header and footer (container was move to inner level)
=> feat: Fixed page payout (palm.master)

.tx/config, Makefile, package-lock.json, package.json
Backport of https://github.com/openedx/frontend-app-communications/pull/164 to `quince.master`.
=> [Quince backport] feat!: remove broken transifex and use atlas exclusively

Makefile
This pull request is part of the [FC-0012 project](https://openedx.atlassian.net/l/cp/XGS0iCcQ) which implements the [Translation Infrastructure update OEP-58](https://docs.openedx.org/en/latest/developers/concepts/oep58.html).
=> feat: add ATLAS_OPTIONS and lib-components and frontend-platform deps | FC-0012

catalog-info.yaml
per https://openedx.atlassian.net/wiki/spaces/COMM/pages/3555852316/GitHub+Access+Team+Structure
=> build: update catalog-info team frontend-all to committers-frontend

README.rst
This will fix typos, add code-blocks and highlighting for better readability
=> fix: update README.rst

package-lock.json, package.json
Part 1 of https://github.com/openedx/frontend-app-communications/issues/216
=> chore: update `@openedx` dependencies to versions that support React 18

.gitignore, package-lock.json, package.json, src/components/page-container/PageContainer.jsx, src/plugin-slots/FooterSlot/README.md, src/plugin-slots/README.md
https://app.pr-226-d404b0.sandboxes.opencraft.hosting/communications/courses/course-v1:demo+Course+1/bulk_email
=> feat: import `FooterSlot` from component package instead of slot package

package-lock.json
I opted to regenerate package lock here.
=> sync `master` -> `master-design-tokens`
