openedx/frontend-app-communications

src/components/bulk-email-tool/BulkEmailTaskManager.jsx
src/components/bulk-email-tool/BulkEmailTool.jsx
src/components/bulk-email-tool/bulk-email-task-manager/BulkEmailContentHistory.jsx
src/components/bulk-email-tool/bulk-email-task-manager/BulkEmailPendingTasks.jsx
src/components/bulk-email-tool/bulk-email-task-manager/BulkEmailTaskHistory.jsx
src/components/bulk-email-tool/bulk-email-task-manager/BulkEmailTaskManager.jsx

[MICROBA-1621]
* Adds a section for the pending tasks section of the task manager
* Adds a section for the bulk course email task history data
* Adds a section for the bulk course email content history data

feat: Add some basic scaffolding for the bulk email tool task manager section of the comms MFE

---

src/components/bulk-email-tool/BulkEmailTool.jsx

This will protect the bulk email tool and ONLY the bulk email tool from non-staff users if they know the direct URL. this will not protect the entire app from non-staff entirely.
This PR adds a spinner, and then shows the app to the user if `is_staff` is true. Otherwise, it will show an error page.

feat: protect bulk email from non staff

---

package-lock.json
package.json
webpack.prod.config.js

During our CI checks on PRs, we check to see if all code can be properly
transpiled into es5 to support IE11. We've since dropped support
officially for IE11, but the check is still present. A dependency of
TinyMCE is triggering an error in the is-es5 check.
Adding this webpack config will except the package from the check, to
prevent the CI from failing. Since we no longer support IE11, This check
is not needed, and ok to bypass.

chore: Add exception for non es5 transpiled dep

---

src/components/bulk-email-tool/bulk-email-task-manager/BulkEmailContentHistory.jsx
src/components/bulk-email-tool/bulk-email-task-manager/messages.js

[MICROBA-1621]
* Add table that displays info about previously sent bulk course email messages through our tool.
* Add modal to view the contents of previously sent messages.
* Extract strings to a dedicated `messages.js` file to help make the `BulkEmailContentHistory.jsx` component more readable.
Screenshots:
Before button is clicked and the table is displayed:
Modal when the "View Message" link is clicked
Warning Alert with message when there is no data to display:
Error Alert with message when we could not fetch our data:

feat: Add historical email content data to bulk course email task manager

---

src/components/bulk-email-tool/bulk-email-task-manager/BulkEmailContentHistory.jsx
src/components/bulk-email-tool/bulk-email-task-manager/BulkEmailHistoryTable.jsx
src/components/bulk-email-tool/bulk-email-task-manager/BulkEmailPendingTasks.jsx
src/components/bulk-email-tool/bulk-email-task-manager/BulkEmailTaskHistory.jsx
src/components/bulk-email-tool/bulk-email-task-manager/BulkEmailTaskManager.jsx
src/components/bulk-email-tool/bulk-email-task-manager/messages.js
src/utils/useInterval.js

[MICROBA-1621]
* Add a table to the BulkEmailTaskHistory component of the task manager.
* Add a table to the BulkEmailPendingTasks component of the task manager.
* Extract messages to messages.js.
* Add custom hook used to make REST API calls to edx-platform on a regular cadence (every 30 seconds).
* Use the new hook in BulkEmailPendingTasks to retrieve pending instructor tasks for display in a table.
Screenshots:
**Pending Tasks table**
**Pending Tasks table (empty)**
**Email Task History**
**Email Task History (empty)**

feat: Implement task history and pending task tables

---

src/components/bulk-email-tool/bulk-email-form/BulkEmailForm.jsx
src/components/bulk-email-tool/bulk-email-form/BulkEmailRecipient.jsx

Add/move instructions for submitting the email form.
Also fixes a sneaky bug when selecting cohorts.

fix: [MICROBA-1703] Add missing form instructions

---

src/components/bulk-email-tool/bulk-email-form/BulkEmailForm.jsx
src/components/bulk-email-tool/bulk-email-form/bulk-email-recipient/BulkEmailRecipient.jsx
src/components/bulk-email-tool/bulk-email-form/bulk-email-recipient/bulkEmailRecepient.scss
src/components/bulk-email-tool/bulk-email-form/bulk-email-recipient/index.js

There was a small issue with the cohorts looking a little weird in the
checkbox list. This even out the list and forces each item to be the
same size.
Desktop:
Mobile:
Desktop:
Mobile:

fix: [MICROBA-1709] Fix cohort display bug

---

package-lock.json
package.json
webpack.dev.config.js
webpack.prod.config.js

[MICROBA-1743]
Fixes an issue where we couldn't override the header and footer with the branded versiom within the Comms MFE because some of the dependencies of the branded components are not currently Webpack5 compliant. Adds a rule to make webpack5 less strict with imports that do not include a file extension.
This also includes a change so that the Comms MFE uses the Open edX branded colors/styles by default.

fix: Update webpack config to be less strict

---

src/components/bulk-email-tool/text-editor/TextEditor.jsx

Image uploads were broken for 2 reasons on stage:
1. Our bleaching on the server was too strong. it was pulling out
attributes inside of the image tags that allowed base64 encoding to
work properly.
2. The paste_data_images needs to be set to true to allow for dragging
and dropping of images into the editor
Since bleach has been rolled back for now, adding this setting should
allow for images to be properly uploaded.

fix: [Microba-1741] Fix email image upload

---

src/components/bulk-email-tool/text-editor/TextEditor.jsx

Reverts edx/frontend-app-communications#25
We don't need this change after all because we don't support drag-and-drop in the editor

Revert "fix: [Microba-1741] Fix email image upload"

---

src/components/page-container/PageContainer.jsx
src/components/page-container/PageContainer.scss

[MICROBA-1743]
* Add styling overrides for images and text in header to make logo sizes consistent in the PageContainer component.
Before:
After:

fix: fix oversized logo in header

---

src/components/bulk-email-tool/text-editor/TextEditor.jsx

The new plugin for code blocks is in the sameplace as the old one, and the HTML editor is back in the old spot as well.

fix: [MICROBA-1760] code block on toolbar

---

public/index.html
src/components/bulk-email-tool/text-editor/TextEditor.jsx

- Missing left align tool (just a typo)
- Missing advanced image options (missing configuration)
- Page title was never set
Other issues such as email title, google+, and sender address are not
related to the MFE and are quirks to do with the staging environment.
left align
image advanced tab (ignore the modal styling I dont have the edX theme on)
tab name

fix: Support feedback of tool

---

src/components/bulk-email-tool/text-editor/TextEditor.jsx

For some reason, the emoticons toolbar was causing errors and making messages cut off. For now, we're just going to disable the tool on the toolbar.

fix: disable emoticons to prevent messages from being cut off

---

src/components/bulk-email-tool/bulk-email-form/TaskAlertModal.jsx
src/components/bulk-email-tool/text-editor/TextEditor.jsx

Course teams were having issues sending bulk emails to themselves and
students. This was caused by two problems.
1. The language selector tool was failing because of no default language
settings in safari is possible
2. The translated string for the "continue" button on the submit modal
was messing with the markup and causing the event to POST the email
to not properly fire.
To fix the language issue for now, we are disabling the language
selector plugin. To fix the markup issue, we are forcing the string to
render in a fragment to remove the additional span, allowing the event
to fire no matter where the user clicks the button.

fix: [MICROBA-1799] fix bulk email tool on safari

---

src/components/bulk-email-tool/data/BulkEmailProvider.jsx
src/components/bulk-email-tool/data/actions.js
src/components/bulk-email-tool/data/api.js
src/components/bulk-email-tool/data/reducer.js
src/components/bulk-email-tool/data/test/__factories__/courseEmail.factory.js
src/components/bulk-email-tool/data/test/__factories__/scheduledEmails.factory.js
src/components/bulk-email-tool/data/test/reducer.test.js
src/components/bulk-email-tool/data/thunks.js
src/utils/useAsyncReducer.js

Currently, our bulk email tool in concept looks something like this:
- BulkEmailTool
- BulkEmailForm
- BulkEmailTaskManager
Right now, the two components under the parent BulkEmailTool dont really
need to communicate with each other. For scheduled email, these two
components are going to be relying on the same data, and there need to
be provided that data by the parent. In order to make things more
manageable, this PR sets up some boilerplate and patterning for this
data. What this PR will include:
- Necessary boilerplate to leverage the context store for the
BulkEmailTool
- Tests around said store
What this PR will not include:
- Changes to the UI or form functionality

feat: [MICROBA-1506] bulkEmailTool data context

---

src/components/bulk-email-tool/bulk-email-task-manager/BulkEmailContentHistory.jsx
src/components/bulk-email-tool/bulk-email-task-manager/ViewEmailModal.jsx

This pr extracts out the message modal so that it can be reused
elsewhere in the app. Specifically so we can reuse it for the "view"
button in the scheduled emails table.

refactor: [MICROBA-1506] refactor message modal

---

src/components/bulk-email-tool/BulkEmailTool.jsx
src/components/bulk-email-tool/bulk-email-form/BulkEmailForm.jsx
src/components/bulk-email-tool/bulk-email-form/ScheduleEmailForm.jsx
src/components/bulk-email-tool/bulk-email-form/bulk-email-recipient/BulkEmailRecipient.jsx
src/components/bulk-email-tool/bulk-email-form/bulk-email-recipient/bulkEmailRecepient.scss
src/components/bulk-email-tool/bulk-email-form/bulkEmailForm.scss
src/components/bulk-email-tool/bulk-email-form/messages.js
src/components/bulk-email-tool/bulk-email-form/test/BulkEmailForm.test.jsx
src/components/bulk-email-tool/bulk-email-task-manager/BulkEmailContentHistory.jsx
src/components/bulk-email-tool/bulk-email-task-manager/BulkEmailPendingTasksAlert.jsx
src/components/bulk-email-tool/bulk-email-task-manager/BulkEmailTaskHistory.jsx
src/components/bulk-email-tool/bulk-email-task-manager/BulkEmailTaskManager.jsx
src/components/bulk-email-tool/bulk-email-task-manager/bulkEmailTaskHistory.scss
src/components/bulk-email-tool/bulk-email-task-manager/messages.js
src/components/bulk-email-tool/bulk-email-task-manager/test/BulkEmailContentHistory.test.jsx
src/components/bulk-email-tool/bulk-email-task-manager/test/BulkEmailTaskHistory.test.jsx
src/components/navigation-tabs/BackToInstructor.jsx
src/components/navigation-tabs/NavigationTabs.jsx

This PR removes the Pending Tasks table from the Bulk Email tool. In addition, a handful of styling changes were made as well as other updates to ensure we are meeting accessibility standards.
**Navigation:**
- Navigation menu is now set up as Tabs
- "Back to Instructor Dashboard" link positioned underneath nav
**Email Form**
- Checkboxes in form refactored to meet the Figma design and be responsive
**Scheduling**
_There seem to be a couple errors with the scheduling functionality that I noticed as I was taking these screenshots._
_One is triggered when toggling off the "Schedule this email for a future date" checkbox (I believe this has to do with a function imported from BulkEmailContext). Another triggers when typing the year into the date input (this is has to do with the …

WIP - Removing Pending tasks and styling changes - Microba 1824

---

src/components/bulk-email-tool/bulk-email-form/BulkEmailForm.jsx
src/components/bulk-email-tool/bulk-email-form/data/reducer.js
src/components/bulk-email-tool/bulk-email-task-manager/bulk-email-scheduled-emails-table/BulkEmailScheduledEmailsTable.jsx
src/components/bulk-email-tool/bulk-email-task-manager/bulk-email-scheduled-emails-table/test/BulkEmailScheduledEmailsTable.test.jsx
src/utils/useTimeout.js

Right now, canceling edit mode is clunky. This adds a button to explicitly cancel the mode for the editor.
When editing:
Hover:

feat: Add cancel button for editing an email

---

src/components/bulk-email-tool/bulk-email-form/BulkEmailForm.jsx
src/components/bulk-email-tool/bulk-email-form/data/actions.js
src/components/bulk-email-tool/bulk-email-form/data/reducer.js

The various form states were getting mixed up during error handling,
which lead to some strange situations where the cancel button was
appearing when it shouldnt have been. This PR centralizes all of the
form state changes into a useEffect hook to handle any and all state
changes throughout the form. This approach not only centralizes the
fragmented code, but prevents the state mixups that were happening
previously.
It also has the added benefit if down the line more state changes need
to be added, the changes are all happening in one place.

fix: [MICROBA-1905] fix cancel button

---

src/components/bulk-email-tool/bulk-email-form/BulkEmailForm.jsx

The form wasn't awaiting the post/patch calls when creating new emails. Then when it went to update the scheduled emails table, it did not update properly. this fixes the issue, and the table will now update after the new email is posted.

fix: await post to properly update form

---

src/components/bulk-email-tool/bulk-email-form/BulkEmailForm.jsx
src/components/bulk-email-tool/bulk-email-form/ScheduleEmailForm.jsx
src/components/bulk-email-tool/bulk-email-form/test/BulkEmailForm.test.jsx
src/components/bulk-email-tool/bulk-email-task-manager/bulk-email-scheduled-emails-table/BulkEmailScheduledEmailsTable.jsx
src/utils/formatDateAndTime.js

Currently, we do not validate date and time to be a date on the future on the front end. We do handle this on the backend. This updates form validation to force the user to enter a data in the future.

fix: [MICROBA-1903] validate date time

---

src/components/bulk-email-tool/bulk-email-form/BulkEmailForm.jsx
src/components/bulk-email-tool/bulk-email-form/bulk-email-recipient/BulkEmailRecipient.jsx
src/components/bulk-email-tool/bulk-email-form/data/__factories__/bulkEmailFormCohort.factory.js
src/components/bulk-email-tool/bulk-email-form/test/BulkEmailForm.test.jsx

[Update] The original PR misunderstood what the ticket was asking for. We actually DO NOT want to check any learner boxes, but instead simply disable them when "All Learners" is checked. This still gets the point across that all learners will be sent an email while not bogging down the backend with duplicated requests. The latest push to this PR addresses this and ensures that it works for any added cohorts as well. There is also a test for this new functionality.
[Updated video]
https://user-images.githubusercontent.com/92897870/182911869-5dbb8eef-9fb8-4884-b3a2-ab913015fd28.mov
[Original comment, can be ignored]
This PR addresses one of the issues brought up during the bug bash. Cohorts were not getting checked when "All learners" was selected, however, emails were still being sent. We …

Unchecking and disabling boxes when "All Learners" is selected

---

src/components/bulk-email-tool/BulkEmailTool.jsx
src/components/bulk-email-tool/bulk-email-task-manager/BulkEmailContentHistory.jsx
src/components/bulk-email-tool/bulk-email-task-manager/BulkEmailPendingTasksAlert.jsx
src/components/bulk-email-tool/bulk-email-task-manager/test/BulkEmailContentHistory.test.jsx
src/components/page-container/PageContainer.jsx

changes as per the a11y review shake out as follows:
> The SkipNav link (Skip to main content) should jump to the H1 or to a link just above the H1, which would show on focus (you could use the same style as the SkipNav link to do this).
The skipNav link now properly anchors to the `H1`:
---
> The <html> element needs a lang attribute
---
> The page needs a unique <title> (text used for the browser tab) in the <head>.
---
> The label Body above the TinyMCE editor has a for= attribute that points to a missing ID. I think that ID should be on the `<textarea>` just below it (not the `<div role="application">`). I'm not 100% sure on that but please add it to confirm.
As far as I can tell, this is done correctly, as the role is where the `TinyMCE` editor starts:
`The application role indicates …

fix: [APER-1936] Changes for a11y review

---

package-lock.json
package.json

Fixes the Comms MFE build by updating `frontend-platform` to 2.6.1. 
We recently updated the branded header and footer in `edx-internal` which requires a build of `frontend-platform` 2.4+, currently we are using 1.15.x. 
We also need to update the non-branded header and footer in this PR as the 10.x and 2.x versions are not compatible with frontend-platform < 2.3.x.

fix: fix build by updating frontend-platform to v2.6.1

---

.github/workflows/ci.yml
package-lock.json
package.json

Ticket:
[Use shared @edx/browserslist-config](https://github.com/openedx/frontend-wg/issues/47)
* Removes custom `browserslist` configuration in favor of using a [shared configuration](https://github.com/edx/browserslist-config).
* Removes `is-es5` check in CI since ES5 was only needed for IE 11 support which is dropped. The supported browsers defined by the shared configuration all [natively support ES6](https://caniuse.com/?search=es6).
This change reduces the resultant asset bundle size.

build: use shared browserslist configuration

---

renovate.json

[Create common renovate config that automates @edx namespaced minor/patch version upgrades](https://github.com/openedx/frontend-wg/issues/116)
Added Renovate config to update and auto merge `@edx` name spaced minor and patch packages.
As no schedule is provided, it will create and merge renovate PRs at any time

Renovate config to automate @edx namespaced minor/patch version upgrade

---

package-lock.json
package.json

Ticket
[Migrate from Coveralls to Codecov ](https://github.com/openedx/frontend-wg/issues/9)
Codecov NodeJS Uploader [package](https://www.npmjs.com/package/codecov) is depreciated since version 3.8.3
This PR move the coverage to CI according to the new guidelines and [depreciation](https://about.codecov.io/blog/codecov-uploader-deprecation-plan/) plan of codecov

Remove unused codecov package

---

src/components/page-container/data/api.js
src/components/page-container/data/api.test.js

frontend-platform supports runtime configuration since 2.5.0 (see the PR that introduced it[1], but it requires MFE cooperation.  This implements just that: by avoiding making configuration values constant, it should now be possible to change them after initialization.
Only a single change related to the `LMS_BASE_URL` setting was required.
[1] openedx/frontend-platform#335

feat: Support runtime configuration

---

src/components/bulk-email-tool/text-editor/TextEditor.jsx

fixes https://github.com/openedx/wg-build-test-release/issues/294
The default behavior of the TinyMCE editor is to rewrite links that share the same domain as the component to be relative to that path. Relative URLs will never work in email contents, so they _always_ need to be absolute URLs. This adds the configuration settings for `relative_urls` and `remove_script_host` in TinyMCE to always be false, enabling it to always use absolute URLs. See
[here](https://www.tiny.cloud/docs/configure/url-handling/) for reference.

fix: Disable URL rewriting when creating links

---

src/components/bulk-email-tool/text-editor/TextEditor.jsx

cherry-pick of 765857f380a6104dc9d3af6eba803bf45bed58a4
The default behavior of the TinyMCE editor is to rewrite links that share the same domain as the component to be relative to that path. Relative URLs will never work in email contents, so they _always_ need to be absolute URLs. This adds the configuration settings for `relative_urls` and `remove_script_host` in TinyMCE to always be false, enabling it to always use absolute URLs. See
[here](https://www.tiny.cloud/docs/configure/url-handling/) for reference.

backport of PR #134 -- fix: Disable URL rewriting when creating links

---

src/components/page-container/data/api.js
src/components/page-container/data/api.test.js

(This is a backport of #125 to Palm.)
frontend-platform supports runtime configuration since 2.5.0 (see the PR that introduced it[1], but it requires MFE cooperation. This implements just that: by avoiding making configuration values constant, it should now be possible to change them after initialization.
Only a single change related to the LMS_BASE_URL setting was required.
[1] https://github.com/openedx/frontend-platform/pull/335

[Palm] feat: Support runtime configuration

---

README.rst

The README of the MFE's need to be updated because the frontend app template has been updated
Issue related: https://github.com/openedx/wg-frontend/issues/169

[DOCS] Readme updated according OEP-55

---

.github/workflows/lockfileversion-check.yml

Renamed `lockfileversion-check-v3` to `lockfile-check` in lockfile version file.
[Prototype a way to review NPM lockfiles in PRs](https://github.com/edx/edx-arch-experiments/issues/355)

refactor: updated lock file version check to use new workflow 

---

public/index.html

The favicon is not currently displaying in Safari. After our investigation, we have found a way to fix it. We used the same approach as what was done in the account mfe. We added the favicon inclusion to the index.html file, and now the favicon is being displayed in Safari.

fix: Missed favicon in Safari (backport form master)

---

src/components/bulk-email-tool/BulkEmailTool.jsx
src/components/page-container/PageContainer.jsx

There is a wrong `main-content` identificator placement, in the `src/components/page-container/PageContainer.jsx` component. For now, it's located at `h1` tag `<h1 className="text-primary-500" id="main-content">`.  As a shown on screen below, in other MFE this id allocated to the `<main>` tag, this fix going to make more consistent look with other applications and to prevent errors associated with this identificator.

fix: wrong id placement on the h1 tag

---

.tx/config
Makefile
package-lock.json
package.json

Transifex integration never worked for the communication MFE. This pull request updates the MFE to use `atlas pull` exclusively.
References
----------
This contribution is part of the [FC-0012 project](https://openedx.atlassian.net/l/cp/XGS0iCcQ) which is sparked by the [Translation Infrastructure update OEP-58](https://open-edx-proposals.readthedocs.io/en/latest/architectural-decisions/oep-0058-arch-translations-management.html#specification).

feat!: remove broken transifex and use atlas exclusively | FC-0012

---

src/components/bulk-email-tool/bulk-email-form/ScheduleEmailForm.jsx
src/components/bulk-email-tool/bulk-email-task-manager/bulk-email-scheduled-emails-table/BulkEmailScheduledEmailsTable.jsx

This pull request contains fix for correct date and time displaying depends on user locale date/time format.
In locations like `uk-UA` where the date format `DD.MM.YYYY` the date didn't set to the form on edit button click because of incorrect format for transforming it by `new Date()` constructor.
Current solution covers cases for different date formats in the form controls and text displaying of these dates.
|  en-US |  uk-UA |  en-GB  |
|---|---|---|
|  <img width="1017" alt="image" src="https://github.com/openedx/frontend-app-communications/assets/17108583/535d3e6b-702a-4b38-a5b0-3a1c2c2a874c"> |  <img width="1012" alt="image" src="https://github.com/openedx/frontend-app-communications/assets/17108583/2b0bec28-3425-4200-9f79-53c3961f6deb"> |  <img width="1007" alt="image" …

fix: date format depends on locale date format

---

src/components/bulk-email-tool/bulk-email-form/BulkEmailForm.jsx
src/components/bulk-email-tool/bulk-email-form/messages.js

If the user puts more than 128 symbols in the email subject it causes an error.
Added length restriction and field tip.
Related PR: https://github.com/openedx/frontend-app-communications/pull/154

fix: Added maxLength and default tip for email subject

---

src/components/bulk-email-tool/BulkEmailTool.jsx
src/components/bulk-email-tool/bulk-email-form/BulkEmailForm.jsx
src/components/bulk-email-tool/bulk-email-form/bulk-email-recipient/BulkEmailRecipient.jsx
src/components/bulk-email-tool/bulk-email-form/data/__factories__/bulkEmailFormCourseMode.factory.js
src/components/bulk-email-tool/bulk-email-form/test/BulkEmailForm.test.jsx
src/components/page-container/PageContainer.jsx

The Communication MFE has course mode checkboxes hardcoded, so a user can select any of them even if the course has no such mode.
As a result - they will get an error when trying to send emails to learners of the track (course mode) that doesn't exist.
The goal here is to provide course mode checkboxes for real course modes only.

fix: hardcoded course mode checkboxes

---

src/components/bulk-email-tool/bulk-email-form/BulkEmailForm.jsx
src/components/bulk-email-tool/bulk-email-form/messages.js

Add limitation for subject length (128 chars) and the
corresponding help text.
This is a backport from the master branch: https://github.com/openedx/frontend-app-communications/pull/154

fix: limit email subject length

---

Makefile

In https://github.com/openedx/frontend-app-course-authoring/pull/1208 we merged `frontend-lib-content-components` into `frontend-app-course-authoring`, and there is no remaining usage of `frontend-lib-content-components` so we will soon be archiving that repo.
@OmarIthawi noticed that there is a reference to that deprecated `frontend-lib-content-components` repo in this project. It's unclear to me what it was supposed to be doing, so I'm just removing it for now. As far as I can tell, this app does not actually relate to `frontend-lib-content-components`, and there are no references to it in the code.

Remove reference to deprecated frontend-lib-content-components repo

---

src/components/bulk-email-tool/bulk-email-task-manager/BulkEmailTaskManager.jsx
src/components/bulk-email-tool/bulk-email-task-manager/ViewEmailModal.jsx
src/components/bulk-email-tool/bulk-email-task-manager/bulk-email-scheduled-emails-table/BulkEmailScheduledEmailsTable.jsx
src/components/bulk-email-tool/task-alert-modal/TaskAlertModal.jsx

Closes https://github.com/openedx/frontend-app-communications/issues/244
Replacing the usage of `injectInt` HOC with `useIntl()` hook from `@edx/frontend-platform/i18n` and all related code.
Most of the refactor of the files was made using this codemon: https://github.com/WGU-Open-edX/oex-utils/tree/main/intl-modernizer.

refactor: replacing injectIntl with useIntl part 2

---

src/components/bulk-email-tool/bulk-email-form/BulkEmailForm.jsx
src/components/bulk-email-tool/bulk-email-task-manager/BulkEmailContentHistory.jsx
src/components/bulk-email-tool/bulk-email-task-manager/BulkEmailPendingTasks.jsx
src/components/bulk-email-tool/bulk-email-task-manager/BulkEmailTaskHistory.jsx

Closes https://github.com/openedx/frontend-app-communications/issues/243
Replacing the usage of `injectInt` HOC with `useIntl()` hook from `@edx/frontend-platform/i18n` and all related code.
Most of the refactor of the files was made using this codemon: https://github.com/WGU-Open-edX/oex-utils/tree/main/intl-modernizer.

refactor: replacing injectIntl with useIntl part 1

---

src/components/bulk-email-tool/text-editor/TextEditor.jsx
webpack.dev.config.js
webpack.prod.config.js

This pull request proposes fixing the margin around the body element. This margin comes from the tinyMCE styles. In cases where we don't have a custom theme, and the header and footer are white, it's not noticeable (1st screenshot). However, if the header and footer have any color, it immediately stands out (2nd and 3rd screenshots). The `important` property is set not by chance, as without it, the styles from the tinyMCE override the styles from the index.scss file.

fix: Remove extra margin around body element
